import type { ImageSourcePropType } from "react-native";
import rawLessons from "./lessons.json";

export type LessonWord = {
  id: string;
  word: string;
  image?: ImageSourcePropType;
  imageLabel: string;
  imageCaption: string;
  sentence: string;
  phoneticHint: string;
  phoneticSound: string;
  missingLetterPrompt: string;
  missingLetterAnswer: string;
  missingLetterOptions: string[];
};

export type ScenarioLesson = {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  coverImage?: ImageSourcePropType;
  seedWords: string[];
  words: LessonWord[];
};

// Static image registry required by React Native / Metro Bundler
// Automatically generated by scripts/generate-assets.js
export const LESSON_IMAGES: Record<string, ImageSourcePropType> = {
  "pagbebenta/presyo.webp": require("../../assets/lessons/pagbebenta/presyo.webp"),
  "pagbebenta/sukli.webp": require("../../assets/lessons/pagbebenta/sukli.webp"),
  "pagbebenta/bayad.webp": require("../../assets/lessons/pagbebenta/bayad.webp"),
  "pagbebenta/tinda.webp": require("../../assets/lessons/pagbebenta/tinda.webp"),
  "pagmamaneho/preno.webp": require("../../assets/lessons/preno.webp"),
  "pagmamaneho/ilaw.webp": require("../../assets/lessons/pagmamaneho/ilaw.webp"),
  "pagmamaneho/daan.webp": require("../../assets/lessons/pagmamaneho/daan.webp"),
  "phone-buttons/send.webp": require("../../assets/lessons/phone-buttons/send.webp"),
  "phone-buttons/save.webp": require("../../assets/lessons/phone-buttons/save.webp"),
  "phone-buttons/back.webp": require("../../assets/lessons/phone-buttons/back.webp"),
};

export const scenarioLessons: ScenarioLesson[] = (rawLessons as any[]).map((lesson) => ({
  id: lesson.id,
  title: lesson.title,
  shortTitle: lesson.shortTitle,
  description: lesson.description,
  coverImage: LESSON_IMAGES[lesson.coverImageKey],
  seedWords: lesson.seedWords,
  words: lesson.words.map((word: any) => ({
    id: word.id,
    word: word.word,
    image: LESSON_IMAGES[word.imageKey],
    imageLabel: word.imageLabel,
    imageCaption: word.imageCaption,
    sentence: word.sentence,
    phoneticHint: word.phoneticHint,
    phoneticSound: word.phoneticSound,
    missingLetterPrompt: word.missingLetterPrompt,
    missingLetterAnswer: word.missingLetterAnswer,
    missingLetterOptions: word.missingLetterOptions,
  })),
}));

export const defaultScenario = scenarioLessons[0];
